"""create raw_vitivinicultura_current

Revision ID: adae35424e47
Revises: 
Create Date: 2025-05-17 17:01:06.219165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adae35424e47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_vitivinicultura',
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('subopcao', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('endpoint', 'ano', 'subopcao'),
    schema='vitivinicultura'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_vitivinicultura', schema='vitivinicultura')
    # ### end Alembic commands ###
